### ISSUE TITLE
parse_name() issues with title "miss"

### ISSUE THREAD

**Issue by sap218** [vaneseltine/nominally#54]
Currently reviewing as part of https://github.com/openjournals/joss-reviews/issues/3440

The examples provided work as expected - however when using my own examples:

`parsed = nominally.parse_name("Miss Samantha Clare Pendleton")` - output not as expected and title blank / instead `"first":"miss"`

`parsed = nominally.parse_name("Ms Samantha Clare Pendleton")` - output as expected

`parsed = nominally.parse_name("Mrs Samantha Clare Pendleton")` - output as expected

All outputs are as expected except for "Miss" which parse_name() function cannot identify as a title

**Comment by vaneseltine** [comment]
Thanks for filing this issue! In reviewing the title list, I also added [Mx](https://en.wikipedia.org/wiki/Mx_(title)) to bring the total to `TITLES = {"dr", "miss", "mr", "mrs", "ms", "mx"}`

Additional thoughts: There are many additional titles that could be added (see Wikipedia on [English honorifics](https://en.wikipedia.org/wiki/English_honorifics) or [Titles in English-speaking areas](https://en.wikipedia.org/wiki/Title#Titles_in_English-speaking_areas); cf. [python-nameparser's extensive list](https://github.com/derek73/python-nameparser/blob/master/nameparser/config/titles.py)) but I'd like to keep the false-positive title labeling low. In record linkage across different data sources, titles are unlikely to have a strong signal -- it would be a rare circumstance where Mr or Dr or Miss are helpful determinants of matching. This short list can be safely excluded entirely. Better to keep a title as an extraneous name than to throw away a potentially useful name such as [Sir](https://www.wolframalpha.com/input/?i=name+sir).
